if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/abundance_milo_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/abundance_milo_correctness[1]_tests.cmake")
else()
  add_test(abundance_milo_correctness_NOT_BUILT abundance_milo_correctness_NOT_BUILT)
endif()
