if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/anno_celltypist_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/anno_celltypist_correctness[1]_tests.cmake")
else()
  add_test(anno_celltypist_correctness_NOT_BUILT anno_celltypist_correctness_NOT_BUILT)
endif()
