if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/anno_mt_lineage_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/anno_mt_lineage_correctness[1]_tests.cmake")
else()
  add_test(anno_mt_lineage_correctness_NOT_BUILT anno_mt_lineage_correctness_NOT_BUILT)
endif()
