if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/ase_daesc_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/ase_daesc_correctness[1]_tests.cmake")
else()
  add_test(ase_daesc_correctness_NOT_BUILT ase_daesc_correctness_NOT_BUILT)
endif()
