if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/atac_chromvar_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/atac_chromvar_correctness[1]_tests.cmake")
else()
  add_test(atac_chromvar_correctness_NOT_BUILT atac_chromvar_correctness_NOT_BUILT)
endif()
