if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/cna_numbat_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/cna_numbat_correctness[1]_tests.cmake")
else()
  add_test(cna_numbat_correctness_NOT_BUILT cna_numbat_correctness_NOT_BUILT)
endif()
