if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/comm_cellchat_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/comm_cellchat_correctness[1]_tests.cmake")
else()
  add_test(comm_cellchat_correctness_NOT_BUILT comm_cellchat_correctness_NOT_BUILT)
endif()
