if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/disease_scdrs_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/disease_scdrs_correctness[1]_tests.cmake")
else()
  add_test(disease_scdrs_correctness_NOT_BUILT disease_scdrs_correctness_NOT_BUILT)
endif()
