if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/embed_dpt_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/embed_dpt_correctness[1]_tests.cmake")
else()
  add_test(embed_dpt_correctness_NOT_BUILT embed_dpt_correctness_NOT_BUILT)
endif()
