if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/enrich_score_genes_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/enrich_score_genes_correctness[1]_tests.cmake")
else()
  add_test(enrich_score_genes_correctness_NOT_BUILT enrich_score_genes_correctness_NOT_BUILT)
endif()
