if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/fate_palantir_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/fate_palantir_correctness[1]_tests.cmake")
else()
  add_test(fate_palantir_correctness_NOT_BUILT fate_palantir_correctness_NOT_BUILT)
endif()
