if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/generative_discrete_diffusion_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/generative_discrete_diffusion_correctness[1]_tests.cmake")
else()
  add_test(generative_discrete_diffusion_correctness_NOT_BUILT generative_discrete_diffusion_correctness_NOT_BUILT)
endif()
