if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/graph_knn_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/graph_knn_correctness[1]_tests.cmake")
else()
  add_test(graph_knn_correctness_NOT_BUILT graph_knn_correctness_NOT_BUILT)
endif()
