if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/grn_granie_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/grn_granie_correctness[1]_tests.cmake")
else()
  add_test(grn_granie_correctness_NOT_BUILT grn_granie_correctness_NOT_BUILT)
endif()
