if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/gsea_fgsea_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/gsea_fgsea_correctness[1]_tests.cmake")
else()
  add_test(gsea_fgsea_correctness_NOT_BUILT gsea_fgsea_correctness_NOT_BUILT)
endif()
