if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/gsea_aucell_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/gsea_aucell_correctness[1]_tests.cmake")
else()
  add_test(gsea_aucell_correctness_NOT_BUILT gsea_aucell_correctness_NOT_BUILT)
endif()
