if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/integrate_kbet_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/integrate_kbet_correctness[1]_tests.cmake")
else()
  add_test(integrate_kbet_correctness_NOT_BUILT integrate_kbet_correctness_NOT_BUILT)
endif()
