if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/network_hdwgcna_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/network_hdwgcna_correctness[1]_tests.cmake")
else()
  add_test(network_hdwgcna_correctness_NOT_BUILT network_hdwgcna_correctness_NOT_BUILT)
endif()
