if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/perturbation_perturb_graph_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/perturbation_perturb_graph_correctness[1]_tests.cmake")
else()
  add_test(perturbation_perturb_graph_correctness_NOT_BUILT perturbation_perturb_graph_correctness_NOT_BUILT)
endif()
