if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/preprocess_model_gene_var_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/preprocess_model_gene_var_correctness[1]_tests.cmake")
else()
  add_test(preprocess_model_gene_var_correctness_NOT_BUILT preprocess_model_gene_var_correctness_NOT_BUILT)
endif()
