if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/qc_omnidoublet_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/qc_omnidoublet_correctness[1]_tests.cmake")
else()
  add_test(qc_omnidoublet_correctness_NOT_BUILT qc_omnidoublet_correctness_NOT_BUILT)
endif()
