if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/reduce_svd_cv_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/reduce_svd_cv_correctness[1]_tests.cmake")
else()
  add_test(reduce_svd_cv_correctness_NOT_BUILT reduce_svd_cv_correctness_NOT_BUILT)
endif()
