if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/reduce_nmf_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/reduce_nmf_correctness[1]_tests.cmake")
else()
  add_test(reduce_nmf_correctness_NOT_BUILT reduce_nmf_correctness_NOT_BUILT)
endif()
