if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/spatial_flash_deconv_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/spatial_flash_deconv_correctness[1]_tests.cmake")
else()
  add_test(spatial_flash_deconv_correctness_NOT_BUILT spatial_flash_deconv_correctness_NOT_BUILT)
endif()
