if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/streaming_pipeline_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/streaming_pipeline_correctness[1]_tests.cmake")
else()
  add_test(streaming_pipeline_correctness_NOT_BUILT streaming_pipeline_correctness_NOT_BUILT)
endif()
