if(EXISTS "/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/variants_monopogen_correctness[1]_tests.cmake")
  include("/mnt/home/debruinz/Singlet-AI/singlet-gpu/build_cycle157_pearson/tests/variants_monopogen_correctness[1]_tests.cmake")
else()
  add_test(variants_monopogen_correctness_NOT_BUILT variants_monopogen_correctness_NOT_BUILT)
endif()
