# SPDX-License-Identifier: GPL-2.0-or-later
# singlet-gpu/r/R/atac.R
#
# GPU chromVAR-style ATAC motif variability scoring:
#   run_chromvar()   — bias-corrected motif accessibility deviation + p-values
#
# Mirrors the chromVAR R package (Schep et al. 2017 Nat Methods).

#' GPU chromVAR motif accessibility variability scoring
#'
#' Computes bias-corrected per-cell motif accessibility deviations and
#' variability scores using a GPU-native implementation of chromVAR
#' (Schep et al. 2017).
#'
#' @details
#' For each motif, the per-cell deviation is computed as:
#' \deqn{\text{dev}_{m,c} = \frac{O_{m,c} - E_{m,c}}{\sigma_{\text{bg}}}}
#' where \eqn{O_{m,c}} is the observed accessibility score for motif \eqn{m}
#' in cell \eqn{c}, and \eqn{E_{m,c}} is the expected score based on
#' GC-content- and accessibility-matched background peaks.
#'
#' Background peak sampling is reproducibly seeded by \code{seed}.
#' Permutation p-values are generated by shuffling cell labels on device.
#'
#' @param sce                A \code{SingleCellExperiment}.
#' @param motif_in_peak      Named \code{list} with slots \code{row_ptr},
#'   \code{col_idx}, \code{values}, \code{n_rows} (= n_motifs),
#'   \code{n_cols} (= n_peaks).  Binary motif × peak occurrence matrix in CSR
#'   format with 1-based R indices.  Typically built from
#'   \code{motifmatchr::matchMotifs()}.
#' @param peak_gc            \code{NumericVector} [n_peaks], GC content per
#'   peak (0–1).
#' @param peak_mean_access   \code{NumericVector} [n_peaks], mean accessibility
#'   per peak (used for bias-matched background sampling).
#' @param motif_names        \code{CharacterVector} [n_motifs], motif names for
#'   column names in result matrices.  Default: numeric indices.
#' @param peaks_assay        Character. Accessibility assay name.
#'   Default: \code{"peaks"}.
#' @param n_background_peaks Integer. Matched background peaks per peak.
#'   Default: \code{50L}.
#' @param n_permutations     Integer. Permutation count for p-values.
#'   Default: \code{1000L}.
#' @param cell_batch         Integer. Cells per OOC processing batch.
#'   Default: \code{4096L}.
#' @param seed               Integer. RNG seed.  Default: \code{0L}.
#' @param resource           Character. \code{"auto"}, \code{"gpu"}, or
#'   \code{"cpu"}.  Default: \code{"auto"}.
#'
#' @return A named \code{list}:
#' \describe{
#'   \item{\code{deviation}}{\code{NumericMatrix} [n_cells × n_motifs] —
#'     bias-corrected z-score deviations.}
#'   \item{\code{variability}}{\code{NumericVector} [n_motifs] — variance
#'     of deviations across cells.}
#'   \item{\code{p_values}}{\code{NumericMatrix} [n_cells × n_motifs] —
#'     raw permutation p-values.}
#'   \item{\code{p_adj}}{\code{NumericMatrix} [n_cells × n_motifs] —
#'     BH-adjusted p-values per motif.}
#' }
#'
#' @examples
#' \dontrun{
#' cv_res <- run_chromvar(atac_sce,
#'                        motif_in_peak    = jaspar_motif_csr,
#'                        peak_gc          = rowData(atac_sce)$gc,
#'                        peak_mean_access = rowMeans(counts_mat),
#'                        motif_names      = jaspar_names)
#' # Top variable motifs
#' top_motifs <- order(cv_res$variability, decreasing = TRUE)[1:20]
#' }
#'
#' @seealso \code{\link{granie}}, \code{\link{run_ase}}
#' @export
run_chromvar <- function(sce,
                         motif_in_peak,
                         peak_gc,
                         peak_mean_access,
                         motif_names       = character(0),
                         peaks_assay       = "peaks",
                         n_background_peaks = 50L,
                         n_permutations    = 1000L,
                         cell_batch        = 4096L,
                         seed              = 0L,
                         resource          = "auto") {

    .assert_sce(sce, "run_chromvar")

    if (!peaks_assay %in% SummarizedExperiment::assayNames(sce))
        stop(sprintf("run_chromvar: assay '%s' not found in sce.", peaks_assay))

    if (!is.list(motif_in_peak))
        stop("run_chromvar: motif_in_peak must be a named list with slots "
             "row_ptr, col_idx, values, n_rows, n_cols.")

    peak_gc          <- as.double(peak_gc)
    peak_mean_access <- as.double(peak_mean_access)

    access_mat <- SummarizedExperiment::assay(sce, peaks_assay)
    if (!methods::is(access_mat, "dgCMatrix"))
        access_mat <- methods::as(access_mat, "dgCMatrix")

    if (length(motif_names) == 0) motif_names <- character(0)

    chromvar_cpp(
        accessibility       = access_mat,
        motif_in_peak       = motif_in_peak,
        peak_gc             = peak_gc,
        peak_mean_access    = peak_mean_access,
        motif_names         = as.character(motif_names),
        n_background_peaks  = as.integer(n_background_peaks),
        n_permutations      = as.integer(n_permutations),
        cell_batch          = as.integer(cell_batch),
        seed                = as.integer(seed),
        resource            = as.character(resource)
    )
}
