# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read a .1pz file.
#'
#' @description Low-level binding that returns the raw decoded payload as
#'   an R list. Prefer the high-level [read_1pz()] wrapper in `R/read.R`,
#'   which attaches this output into a `Matrix::dgCMatrix` with named
#'   rows and columns.
#'
#' @param path Filesystem path to the ``.1pz`` file.
#' @return A list with the following elements:
#' \describe{
#'   \item{shape}{Integer vector of length 2: (nrows, ncols).}
#'   \item{nnz}{Total number of non-zero entries.}
#'   \item{vt_code}{Writer's value-type hint (1 = uint8, 2 = uint16, 3 = uint32).}
#'   \item{indptr}{Integer vector of length ncols + 1.}
#'   \item{indices}{Integer vector of length nnz — row indices.}
#'   \item{data}{Numeric (double) vector of length nnz — values, promoted
#'     to double so that R can store them without loss.}
#'   \item{rownames}{Character vector of feature names.}
#'   \item{colnames}{Character vector of cell barcodes.}
#'   \item{user_kv}{Named character vector of embedded pipeline metadata
#'     (gsm_id, gse_id, organism, protocol, singlet_version,
#'     pipeline_date, etc.).}
#' }
#' @keywords internal
pz_read_1pz_raw <- function(path) {
    .Call(`_singlet_pz_read_1pz_raw`, path)
}

