# CMake generated Testfile for 
# Source directory: /mnt/home/debruinz/Singlet-AI/singlet/tests/cpp
# Build directory: /mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_pz_reader "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_pz_reader")
set_tests_properties(test_pz_reader PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;39;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_cell_calling "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_cell_calling")
set_tests_properties(test_cell_calling PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;42;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_barcode_rank "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_barcode_rank")
set_tests_properties(test_barcode_rank PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;43;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_cell_qc "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_cell_qc")
set_tests_properties(test_cell_qc PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;44;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_tiny_dataset_guard "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_tiny_dataset_guard")
set_tests_properties(test_tiny_dataset_guard PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;45;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_barcode_metrics "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_barcode_metrics")
set_tests_properties(test_barcode_metrics PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;46;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_mega_sort_params "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_mega_sort_params")
set_tests_properties(test_mega_sort_params PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;49;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_bus_writer "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_bus_writer")
set_tests_properties(test_bus_writer PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;50;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_transcript_compat "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_transcript_compat")
set_tests_properties(test_transcript_compat PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;51;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_barnyard "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_barnyard")
set_tests_properties(test_barnyard PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;52;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_barnyard_route "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_barnyard_route")
set_tests_properties(test_barnyard_route PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;53;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_doublet_scores "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_doublet_scores")
set_tests_properties(test_doublet_scores PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;54;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_saturation_curve "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_saturation_curve")
set_tests_properties(test_saturation_curve PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;55;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_splice_psi "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_splice_psi")
set_tests_properties(test_splice_psi PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;56;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_em_rescue "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_em_rescue")
set_tests_properties(test_em_rescue PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;57;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_metrics_summary "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_metrics_summary")
set_tests_properties(test_metrics_summary PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;58;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_tpm_fpkm "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_tpm_fpkm")
set_tests_properties(test_tpm_fpkm PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;59;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_atac_peaks "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_atac_peaks")
set_tests_properties(test_atac_peaks PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;60;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_protocol_confidence_override "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_protocol_confidence_override")
set_tests_properties(test_protocol_confidence_override PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;61;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_atac_fragment "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_atac_fragment")
set_tests_properties(test_atac_fragment PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;64;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_atac_bin_counter "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_atac_bin_counter")
set_tests_properties(test_atac_bin_counter PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;65;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_atac_qc "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_atac_qc")
set_tests_properties(test_atac_qc PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;66;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_atac_cell_caller "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_atac_cell_caller")
set_tests_properties(test_atac_cell_caller PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;67;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_atac_donor_demux "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_atac_donor_demux")
set_tests_properties(test_atac_donor_demux PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;68;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_atac_ancestry_sex "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_atac_ancestry_sex")
set_tests_properties(test_atac_ancestry_sex PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;69;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_bulk_atac "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_bulk_atac")
set_tests_properties(test_bulk_atac PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;70;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_chipseq "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_chipseq")
set_tests_properties(test_chipseq PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;71;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_cuttag "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_cuttag")
set_tests_properties(test_cuttag PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;72;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_adt_counter "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_adt_counter")
set_tests_properties(test_adt_counter PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;75;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_adt_matcher "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_adt_matcher")
set_tests_properties(test_adt_matcher PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;76;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_hto_demux "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_hto_demux")
set_tests_properties(test_hto_demux PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;77;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_cellplex "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_cellplex")
set_tests_properties(test_cellplex PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;78;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_crispr_guide "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_crispr_guide")
set_tests_properties(test_crispr_guide PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;79;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_species_detect "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_species_detect")
set_tests_properties(test_species_detect PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;82;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_species_registry "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_species_registry")
set_tests_properties(test_species_registry PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;83;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_alignment_qc "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_alignment_qc")
set_tests_properties(test_alignment_qc PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;84;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_sex_calling "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_sex_calling")
set_tests_properties(test_sex_calling PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;85;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_rrna_detect "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_rrna_detect")
set_tests_properties(test_rrna_detect PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;86;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_txome_aligner "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_txome_aligner")
set_tests_properties(test_txome_aligner PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;87;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_nonhost "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_nonhost")
set_tests_properties(test_nonhost PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;90;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_nonhost_aligner "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_nonhost_aligner")
set_tests_properties(test_nonhost_aligner PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;91;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_nonhost_cell_matrix "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_nonhost_cell_matrix")
set_tests_properties(test_nonhost_cell_matrix PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;92;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_nonhost_db_build "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_nonhost_db_build")
set_tests_properties(test_nonhost_db_build PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;93;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_nonhost_em "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_nonhost_em")
set_tests_properties(test_nonhost_em PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;94;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_nonhost_host_filter "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_nonhost_host_filter")
set_tests_properties(test_nonhost_host_filter PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;95;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_nonhost_unmapped_capture "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_nonhost_unmapped_capture")
set_tests_properties(test_nonhost_unmapped_capture PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;96;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_mtx_export "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_mtx_export")
set_tests_properties(test_mtx_export PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;99;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_velocity_export "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_velocity_export")
set_tests_properties(test_velocity_export PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;100;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_fragments_writer "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_fragments_writer")
set_tests_properties(test_fragments_writer PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;101;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_tagged_bam "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_tagged_bam")
set_tests_properties(test_tagged_bam PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;102;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_web_summary "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_web_summary")
set_tests_properties(test_web_summary PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;103;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_summary_json "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_summary_json")
set_tests_properties(test_summary_json PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;104;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_doublet_detect_v2 "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_doublet_detect_v2")
set_tests_properties(test_doublet_detect_v2 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;107;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_ambient_profile "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_ambient_profile")
set_tests_properties(test_ambient_profile PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;108;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_read_dedup_stats "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_read_dedup_stats")
set_tests_properties(test_read_dedup_stats PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;109;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_donor_demux_perf "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_donor_demux_perf")
set_tests_properties(test_donor_demux_perf PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;110;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_wl_ambient "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_wl_ambient")
set_tests_properties(test_wl_ambient PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;111;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_sparse_accumulator "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_sparse_accumulator")
set_tests_properties(test_sparse_accumulator PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;112;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_mt_events "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_mt_events")
set_tests_properties(test_mt_events PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;115;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_rna_variant_caller "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_rna_variant_caller")
set_tests_properties(test_rna_variant_caller PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;116;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_longread "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_longread")
set_tests_properties(test_longread PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;117;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_methyl "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_methyl")
set_tests_properties(test_methyl PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;118;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_mirna "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_mirna")
set_tests_properties(test_mirna PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;119;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_slamseq "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_slamseq")
set_tests_properties(test_slamseq PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;120;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_te_classifier "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_te_classifier")
set_tests_properties(test_te_classifier PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;121;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_te_counter "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_te_counter")
set_tests_properties(test_te_counter PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;122;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_vdj_assembly "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_vdj_assembly")
set_tests_properties(test_vdj_assembly PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;123;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_scdna_cnv "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_scdna_cnv")
set_tests_properties(test_scdna_cnv PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;124;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_hic_contacts "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_hic_contacts")
set_tests_properties(test_hic_contacts PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;125;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_wgs_assembly "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_wgs_assembly")
set_tests_properties(test_wgs_assembly PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;126;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_visium_spatial "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_visium_spatial")
set_tests_properties(test_visium_spatial PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;129;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_visium_qc "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_visium_qc")
set_tests_properties(test_visium_qc PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;130;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_spatial_barcodes "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_spatial_barcodes")
set_tests_properties(test_spatial_barcodes PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;131;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_spatial_multiome "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_spatial_multiome")
set_tests_properties(test_spatial_multiome PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;132;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_combinatorial_barcode "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_combinatorial_barcode")
set_tests_properties(test_combinatorial_barcode PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;135;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_complex_whitelist "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_complex_whitelist")
set_tests_properties(test_complex_whitelist PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;136;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_indrop_detect "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_indrop_detect")
set_tests_properties(test_indrop_detect PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;137;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_seqwell_detect "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_seqwell_detect")
set_tests_properties(test_seqwell_detect PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;138;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_cascade_router "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_cascade_router")
set_tests_properties(test_cascade_router PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;139;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_multiome_router "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_multiome_router")
set_tests_properties(test_multiome_router PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;140;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_interop "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_interop")
set_tests_properties(test_interop PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;141;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_ref_fetch "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_ref_fetch")
set_tests_properties(test_ref_fetch PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;144;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_logging "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_logging")
set_tests_properties(test_logging PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;147;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_interval_tree "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_interval_tree")
set_tests_properties(test_interval_tree PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;148;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_benchmark_suite "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_benchmark_suite")
set_tests_properties(test_benchmark_suite PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;35;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;149;add_pileup_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_h5ad_writer "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_h5ad_writer")
set_tests_properties(test_h5ad_writer PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;159;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;162;add_hdf5_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_loom_writer "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_loom_writer")
set_tests_properties(test_loom_writer PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;159;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;163;add_hdf5_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
add_test(test_molecule_info "/mnt/home/debruinz/Singlet-AI/singlet/build-tests/tests/cpp/test_molecule_info")
set_tests_properties(test_molecule_info PROPERTIES  _BACKTRACE_TRIPLES "/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;159;add_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;164;add_hdf5_test;/mnt/home/debruinz/Singlet-AI/singlet/tests/cpp/CMakeLists.txt;0;")
