// NONHOST-SYLPH-PORT — Unit tests for MinSketchIndex and NonHostScreener
// Run via ctest or standalone:
//   g++ -std=c++17 -O2 -fopenmp -I../include -o /tmp/test_nonhost test/test_nonhost.cpp \
//       && /tmp/test_nonhost

#include "singlet/pileup/nonhost/min_sketch.h"
#include "singlet/pileup/nonhost/nonhost_screener.h"

#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <iostream>
#include <string>
#include <vector>

using namespace singlet::nonhost;

// ── Test helpers ─────────────────────────────────────────────────────────────

static std::string repeat(char c, int n) { return std::string(static_cast<size_t>(n), c); }

// 80-bp non-homopolymer sequences designed to be mutually distinct at k=21.
// Generated by cycling over different 4-base patterns so no 21-mer run is
// all-same-base (which would produce hash=0 and cause false cross-species hits).
static std::string make_seq(const char* pattern, int len = 80) {
    std::string s;
    s.reserve(static_cast<size_t>(len));
    const int plen = static_cast<int>(std::strlen(pattern));
    for (int i = 0; i < len; ++i) s += pattern[i % plen];
    return s;
}

// A 21-mer with a unique fingerprint used in test 4.
// This specific sequence is embedded in both the index and the query,
// guaranteeing it is a k-mer candidate in both.
static const char KNOWN_VIRAL_21MER[] = "ACGTACGTACGTACGTACGTA";

int main() {
    int passed = 0, failed = 0;

    auto PASS = [&](const char* name) {
        ++passed;
        std::cerr << "PASS: " << name << "\n";
    };
    auto FAIL = [&](const char* name, const char* msg) {
        ++failed;
        std::cerr << "FAIL: " << name << " — " << msg << "\n";
    };

    // ── Test 1: Build index from 3 sequences (2 species), verify hit counts ──
    // s1, s2 → species 1;  s3 → species 2
    // Guarantees: querying s1 hits species 1, querying s3 hits species 2.
    // The index is built from those exact sequences, so all their minimizers
    // are present in the index.
    {
        std::string s1 = make_seq("ACGTACGT");      // (ACGT)×10 = 80bp
        std::string s2 = make_seq("CATGCATG");      // (CATG)×10 = 80bp
        std::string s3 = make_seq("GTTACCGT");      // (GTTACCGT)×10 = 80bp

        MinSketchIndex idx = MinSketchIndex::build_from_sequences(
            {{s1, 1u}, {s2, 1u}, {s3, 2u}}, 21, 11, 50000u);

        if (idx.size() == 0) {
            FAIL("test1_build_hit", "index is empty after build");
        } else {
            auto h1 = idx.query(s1);
            auto h3 = idx.query(s3);
            if (h1.count(1u) == 0 || h1.at(1u) == 0)
                FAIL("test1_build_hit", "species 1 not hit when querying s1");
            else if (h3.count(2u) == 0 || h3.at(2u) == 0)
                FAIL("test1_build_hit", "species 2 not hit when querying s3");
            else
                PASS("test1_build_hit");
        }
    }

    // ── Test 2: Serialize/deserialize round-trip; verify hit counts identical ──
    {
        std::string s = make_seq("TGCATGCA");        // (TGCA)×10 = 80bp

        MinSketchIndex idx1 = MinSketchIndex::build_from_sequences(
            {{s, 77u}}, 21, 11, 50000u);

        const char* tmp = "/tmp/test_nonhost_idx.bin";
        bool ok = true;
        try {
            idx1.save(tmp);
        } catch (const std::exception& e) {
            FAIL("test2_roundtrip", e.what());
            ok = false;
        }

        if (ok) {
            MinSketchIndex idx2;
            try {
                idx2 = MinSketchIndex::load(tmp);
            } catch (const std::exception& e) {
                FAIL("test2_roundtrip", e.what());
                ok = false;
            }
        }

        if (ok) {
            MinSketchIndex idx2 = MinSketchIndex::load(tmp);
            auto h1 = idx1.query(s);
            auto h2 = idx2.query(s);

            if (idx1.size() != idx2.size()) {
                FAIL("test2_roundtrip", "size mismatch after load");
            } else if (idx1.k() != idx2.k() || idx1.w() != idx2.w()) {
                FAIL("test2_roundtrip", "k/w mismatch after load");
            } else if (h1.count(77u) == 0 || h2.count(77u) == 0) {
                FAIL("test2_roundtrip", "species 77 not hit after load");
            } else if (h1.at(77u) != h2.at(77u)) {
                FAIL("test2_roundtrip", "hit count changed after save/load");
            } else {
                PASS("test2_roundtrip");
            }
        }
        std::remove(tmp);
    }

    // ── Test 3: classify() returns UNKNOWN for a poly-N sequence ──
    // poly-N has no valid k-mers → extract_minimizers returns empty →
    // classify returns default NonHostHit{} with category=UNKNOWN.
    {
        std::string viral_seq = make_seq("ACGTACGT");
        MinSketchIndex viral_idx = MinSketchIndex::build_from_sequences(
            {{viral_seq, 1u}}, 21, 11);
        MinSketchIndex micro_idx = MinSketchIndex::build_from_sequences({}, 21, 11);
        NonHostScreener screener(viral_idx, micro_idx, 0.01f);

        std::string poly_n(150, 'N');
        auto hit = screener.classify(poly_n);

        if (hit.category != NonHostCategory::UNKNOWN)
            FAIL("test3_unknown_polyN", "expected UNKNOWN for all-N sequence");
        else if (hit.hit_rate != 0.0f)
            FAIL("test3_unknown_polyN", "hit_rate must be 0 for UNKNOWN");
        else
            PASS("test3_unknown_polyN");
    }

    // ── Test 4: classify() returns VIRAL with hit_rate > 0 for a known viral k-mer ──
    // Build the viral index from a reference that contains KNOWN_VIRAL_21MER.
    // Query with the EXACT SAME sequence: all minimizers from the query are in
    // the index, so hit_rate = 1.0 >> 0.01 threshold. Category must be VIRAL.
    {
        // Reference: flanks of CGCG... + KNOWN_VIRAL_21MER + CGCG... (121bp total)
        // Using non-homopolymer flanks so they don't dominate the minimizer window.
        std::string flank = make_seq("CGCGCGCG", 50);
        std::string viral_ref = flank + std::string(KNOWN_VIRAL_21MER) + flank;

        MinSketchIndex viral_idx = MinSketchIndex::build_from_sequences(
            {{viral_ref, 42u}}, 21, 11);
        MinSketchIndex micro_idx = MinSketchIndex::build_from_sequences({}, 21, 11);
        NonHostScreener screener(viral_idx, micro_idx, 0.01f);

        // Query with the SAME sequence → guaranteed to have matching minimizers
        auto hit = screener.classify(viral_ref);

        if (hit.category != NonHostCategory::VIRAL) {
            char buf[128];
            std::snprintf(buf, sizeof(buf),
                "expected VIRAL, got category=%d hit_rate=%.4f hit_count=%u",
                static_cast<int>(hit.category), hit.hit_rate, hit.hit_count);
            FAIL("test4_viral_kmer", buf);
        } else if (hit.hit_rate <= 0.0f) {
            FAIL("test4_viral_kmer", "hit_rate must be > 0");
        } else if (hit.species_id != 42u) {
            FAIL("test4_viral_kmer", "wrong species_id returned");
        } else {
            PASS("test4_viral_kmer");
        }
    }

    // ── Test 5: classify_batch() on 100 reads matches sequential classify() ──
    // 50 reads that share minimizers with the viral index, 50 random non-matching
    // reads. Batch and sequential must agree on all 100 results exactly.
    {
        std::string flank = make_seq("CGCGCGCG", 50);
        std::string viral_ref = flank + std::string(KNOWN_VIRAL_21MER) + flank;

        MinSketchIndex viral_idx = MinSketchIndex::build_from_sequences(
            {{viral_ref, 99u}}, 21, 11);
        MinSketchIndex micro_idx = MinSketchIndex::build_from_sequences({}, 21, 11);
        NonHostScreener screener(viral_idx, micro_idx, 0.01f);

        std::vector<std::string> reads;
        reads.reserve(100);
        for (int i = 0; i < 50; ++i)
            reads.push_back(viral_ref);               // all match virus 99
        for (int i = 0; i < 50; ++i)
            reads.push_back(make_seq("TTTTAAAA", 121)); // won't match anything

        // Sequential reference results
        std::vector<NonHostHit> seq_results;
        seq_results.reserve(100);
        for (const auto& r : reads)
            seq_results.push_back(screener.classify(r));

        // Batch results (may be parallel with OpenMP)
        auto batch_results = screener.classify_batch(reads);

        bool ok = (batch_results.size() == seq_results.size());
        for (size_t i = 0; i < seq_results.size() && ok; ++i) {
            const auto& s = seq_results[i];
            const auto& b = batch_results[i];
            ok = (s.species_id == b.species_id)
              && (s.hit_count  == b.hit_count)
              && (s.category   == b.category)
              && (std::fabs(s.hit_rate - b.hit_rate) < 1e-6f);
        }

        if (ok)
            PASS("test5_batch_consistency");
        else
            FAIL("test5_batch_consistency", "batch results differ from sequential");
    }

    // ── Summary ──────────────────────────────────────────────────────────────
    std::cerr << "\n" << passed << "/" << (passed + failed) << " tests passed\n";
    return (failed > 0) ? 1 : 0;
}
