
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/mnt/home/debruinz/.local/lib/python3.9/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.14.0-570.62.1.el9_6.x86_64 - x86_64
...
